displayName=Bank Gear Slots
author=Ruined Heir
description=Adds equipment slot textures to bank and bank tags tabs
tags=bank gear slots,bank slots,bank tags,tag tabs,equipment,gear,loadout,bank,slot,texture,layout
version=
plugins=com.bankgearslots.BankGearSlotsPlugin
build=standard
